# Generated by Django 4.2.29 on 2026-03-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Manufacturer serial number — applies to all devices', max_length=100, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, help_text='15-digit IMEI — applies to phones and tablets', max_length=20, null=True, unique=True, verbose_name='IMEI Number'),
        ),
    ]
