# Generated by Django 4.2.29 on 2026-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0002_device_serial_number_alter_device_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('country_admin', 'Country Admin'), ('county_focal', 'County Focal Person'), ('subcounty_focal', 'Sub-County Focal Person'), ('cha', 'Community Health Assistant (CHA)')], default='cha', max_length=20),
        ),
    ]
