# Generated by Django 4.2.29 on 2026-03-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHealthPromoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('chu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chps', to='assetapp.communityhealthunit', verbose_name='Community Health Unit')),
            ],
            options={
                'verbose_name': 'Community Health Promoter (CHP)',
                'verbose_name_plural': 'Community Health Promoters (CHPs)',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='chp_assigned_to',
            field=models.ForeignKey(blank=True, help_text='Select if device is assigned to a CHP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='assetapp.communityhealthpromoter', verbose_name='Assigned CHP'),
        ),
    ]
